### ISSUE TITLE
https://conda.anaconda.org vs https://prefix.dev/

### ISSUE THREAD

**Issue by asmith26** [prefix-dev/prefix-dev#44]
Hi there, Firstly thanks for all this amazing work, I've been playing around with pixi and it's been really nice thanks!

**Just wondering, is there much difference/benefits/drawbacks between https://anaconda.org vs https://prefix.dev/?**

It looks like pixi uses anaconda.org by default, just wondering if there are benefits to switching to prefix.dev.

``` bash
$ project channel list --urls
Environment: default
- https://conda.anaconda.org/conda-forge/
```

Thanks for any help!

**Comment by baszalmstra** [comment]
At the moment, prefix.dev mirrors a number of channels from conda.anaconda.org and provides custom channels. At the time of writing, there is always a short delay of at most an hour between prefix.dev because we sync the mirror from the public data available from conda.anaconda.org.

We will be adding some new tech to prefix.dev channels in the next few weeks that will make using prefix.dev channels _much_ faster with pixi. This is based on the community-approved "sharded repodata" [CEP](https://github.com/conda/ceps/pull/75). See also this blog which explains it: https://prefix.dev/blog/sharded_repodata . I assume Anaconda will also be implementing this on their servers at some point. 

Besides the mirror though you can also create your own custom channels and upload your packages there which also benefits from the same technology.

**Comment by asmith26** [comment]
That's really helpful information @baszalmstra , thanks very much for your help and time :)
